# Generated by Django 4.1.7 on 2023-02-26 17:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('register_date', models.DateField(default=datetime.date(2023, 2, 26), verbose_name='Дата добавления пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название магазина')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название предмета')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('payer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping.person', verbose_name='Кто платил')),
                ('shop', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.store', verbose_name='Магазин')),
            ],
        ),
    ]
