# Generated by Django 4.1.7 on 2023-02-26 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(default='stamplevskiyd', max_length=50, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='second_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.SlugField(default=1, max_length=250, unique=True, verbose_name='Никнейм'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='register_date',
            field=models.DateField(default=datetime.date(2023, 2, 26), verbose_name='Дата регистрации'),
        ),
    ]
